---

- name: constraints | python is present
  become: yes
  become_method: sudo
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-simplejson)
  changed_when: False
  tags:
    - constraints
    - python

- name: constraints | ansible meets version requirements
  assert:
    that: "ansible_version.full | version_compare('2.4', '>=')"
    msg: >
      "You must update Ansible to at least 2.4 to use this playbook."
  tags:
    - constraints
    - ansible


# TODO: Check if debian

...
