---

#- name: common | constraints
#  import_tasks: 
#    - constraints.yml
#  tags:
#    - common
#    - constraints

- name: common | packages
  include_tasks: "packages/{{ ansible_pkg_mgr }}.yml"

#- name: common | all packages are latest
#  apt:
#    name: '*'
#    state: latest

...

