FROM debian:stretch

ARG ANSIBLE_VERSION=latest

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    git \
    systemd \
 && rm -rf /var/lib/apt/lists/*

#RUN pip install --upgrade setuptools && pip install ansible

RUN pip install --upgrade setuptools
RUN if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip install ansible; else pip install ansible==${ANSIBLE_VERSION}; fi;
RUN if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip install ansible-lint; fi;

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
